### ISSUE TITLE
Live demo doesn't work

### ISSUE THREAD

**Issue by fadeevab** [jakmeier/paddlers-browser-game#66]
Hi @jakmeier , the live demo of Paddlers doesn't work at this moment:

![image](https://github.com/jakmeier/paddlers-browser-game/assets/5967447/717fa6f8-833f-4663-87c3-676f9db8fcc0)

**Comment by jakmeier** [comment]
Thanks for the report! Looks like the graphql provider is down. Probably has been for a long time, as this has been a dead project for more than a year now.

But timing is perfect, I intend to revive it and play around with it some more very soon. I will look into it then and come back to this issue.

**Comment by jakmeier** [comment]
@fadeevab it should be working again!

**Comment by fadeevab** [comment]
@jakmeier Well, graphql works but the loading stuck on "Construct Buildings"

```
21:12:29.280 Uncaught (in promise) RuntimeError: unreachable executed
    A https://demo.paddlers.ch/1.paddlers.js:1
    c https://demo.paddlers.ch/1.paddlers.js:1
    promise callback*At https://demo.paddlers.ch/1.paddlers.js:1
    __wbg_then_dd3785597974798a https://demo.paddlers.ch/paddlers.js:1
    A https://demo.paddlers.ch/1.paddlers.js:1
    c https://demo.paddlers.ch/1.paddlers.js:1
    promise callback*St https://demo.paddlers.ch/1.paddlers.js:1
    __wbg_then_0f957e0f4c3e537a https://demo.paddlers.ch/paddlers.js:1
    A https://demo.paddlers.ch/1.paddlers.js:1
    c https://demo.paddlers.ch/1.paddlers.js:1
    promise callback*At https://demo.paddlers.ch/1.paddlers.js:1
    __wbg_then_dd3785597974798a https://demo.paddlers.ch/paddlers.js:1
    A https://demo.paddlers.ch/1.paddlers.js:1
    c https://demo.paddlers.ch/1.paddlers.js:1
    promise callback*St https://demo.paddlers.ch/1.paddlers.js:1
    __wbg_then_0f957e0f4c3e537a https://demo.paddlers.ch/paddlers.js:1
    A https://demo.paddlers.ch/1.paddlers.js:1
    c https://demo.paddlers.ch/1.paddlers.js:1
    promise callback*At https://demo.paddlers.ch/1.paddlers.js:1
    __wbg_then_dd3785597974798a https://demo.paddlers.ch/paddlers.js:1
2cd734c2269fba42a7f5.module.wasm:1858893:1

```

**Comment by jakmeier** [comment]
Indeed, you are right. But only for new accounts. At least that's my suspicion, since everything worked fine when I tested with an existing accounts but I see the same problem when I use a new account.

This will need a bit more debugging then. But I hope I will get it resolved tomorrow.

**Comment by jakmeier** [comment]
Well, I had to take off a lot of dust before I could even start debugging this locally. (The code base was depending on a 3 year old rustc nightly with 3 year old packages...) And some more dust had to be removed to get a fix deployed. (old docker images no longer being supported by my hosting provider)

But finally I get passed the loading bar on a newly created player account. (You will need to register again.)

The problem was quite simple. Too many players signed up and I have an unfortunate limit for how far the map can expand. 

```
thread 'actix-rt:worker:3' panicked at 'Village insertion failed: "World full: No space for another village"', src/setup/new_player.rs:66:45
```

I have this fixed on the live demo now.

Sadly, the game is still not playable, as you get stuck in the initial quest state.  There is now a version mismatch between frontend / backends which causes this. I will redeploy everything as-is master soon-ish. But it will require a bit more devops dusting... Hopefully I've pushed through all the pain of reviving this soon. :S

**Comment by fadeevab** [comment]
@jakmeier More problems 🙈
![image](https://github.com/jakmeier/paddlers-browser-game/assets/5967447/d2c8ed7e-ebf6-44aa-8410-757d9b96bff0)

**Comment by jakmeier** [comment]
yeah I know, it's completely broken now :)
work is in progress but I need to re-architecture the container setup, my hosting provider is no longer compatible with official keycloak docker images which is a real petty

**Comment by jakmeier** [comment]
@fadeevab soo, I finally redployed it all in a new setup. And it seems like things work again.

This includes a reset of the DB, all old accounts have been deleted. You will need to register again.

Please take a look and let me know if things are still broken for you. The game isn't much and there are many ugly and rough corners. But there shouldn't be any broken pages at this point. (Maybe you'll need to disable caches for a first load to get the newest JS, any maybe the first page load after registration hangs in the loading page, a refresh should resolve it, however.)

**Comment by fadeevab** [comment]
@jakmeier Alright, I did it!.. However, I can do nothing except click on the duck, and then it says "God visits me" :)

**Comment by jakmeier** [comment]
@fadeevab hm, interesting. So you get to the first dialogue. But the button to go to the next slide doesn't work?

![paddlers_slide_0](https://github.com/jakmeier/paddlers-browser-game/assets/6342444/5e0d0e6d-f314-4b54-8de0-60ba21eb96a4)

**Comment by jakmeier** [comment]
(Once you have clicked through this, you will need to unselect the duck to see the buildings menu to the right side. Then the next step is to click/tap on the blue temple square and then click/tap on where to place it.)

![image](https://github.com/jakmeier/paddlers-browser-game/assets/6342444/a8db26a6-db9e-48e8-a7d4-0d716a07a043)

**Comment by fadeevab** [comment]
@jakmeier I found the problem, in my case the clicking area of the buttons is shifted higher by the vertical axis. FYI, my browser is Firefox.
![image](https://github.com/jakmeier/paddlers-browser-game/assets/5967447/a198a0bd-5804-4ad5-b18b-4258282b415a)

**Comment by jakmeier** [comment]
Thanks for the report @fadeevab!
This happened to me as well the other day. (also in Firerfox). But I wasn't able to replicate it, it only happened to me once. I suspect it might be related to screen resizing and/or debug tabs being open. But again, no luck replicating so far.

For now, I filed https://github.com/jakmeier/paddlers-browser-game/issues/68 to track this problem.

**Comment by fadeevab** [comment]
@jakmeier It was fun to cooperate with you @jakmeier 😊
